### ISSUE TITLE
Error decrypting message

### ISSUE THREAD

**Issue by clluiz** [auth0/passport-wsfed-saml2#103]
I'm trying to login using Samlp but the library is returning the following error:
"Assertion is encrypted. Please set options.decryptionKey with your decryption private key."
Where I get this decryptionKey?

**Comment by gkwang** [comment]
It should be the private key of your certificate.

**Comment by machuga** [comment]
@clluiz Did this answer your question?

**Comment by clluiz** [comment]
@machuga, yes. But I see that I was configuring my adfs server wrong too. Thanks @gkwang !

**Comment by clluiz** [comment]
One more question, where can I find a complete explanation of all the options accepted by the lib?
