### ISSUE TITLE
authentication callback

### ISSUE THREAD

**Issue by davidgithub1980** [auth0/passport-wsfed-saml2#105]
Hi. I would like to clear the usage of the _callback_ used in your examples in 2 places:

1)
**_path: '/login/callback'..._** (used in the wsfedsaml2 constructor)

2)
**_app.post('/login/callback'..._** (used in the express router)

I have a working example that is the copy of your example minus the 2 occurrences of the _callback_. Is there a reason for its presence when the example is clearly working without it? Or is there something fundamentally wrong after removing those pieces?

I simply have:

1)
**_path: '/login'..._**

2)
**_app.post('/login'..._**

Thanks for your clearance.

**Comment by davidgithub1980** [comment]
Yap, my question was more about the necessity to append the _callback_ part to both occurrences above cause it is working well without it.

**Comment by machuga** [comment]
@davidgithub1980 Oh! I see. No the `/callback` suffix is purely optional. You can name the routes anything so long as your configuration knows to send users back to those routes.
