### ISSUE TITLE
Get errror: `TypeError: Cannot set property 'user' of undefined` because old passport dependency

### ISSUE THREAD

**Issue by leomao** [auth0/passport-wsfed-saml2#20]
Get the following error:
```
TypeError: Cannot set property 'user' of undefined  
    at /src/node_modules/passport-wsfed-saml2/node_modules/passport/lib/passport/http/request.js:45:35
    at pass (/src/node_modules/passport/lib/authenticator.js:267:43)
    at serialized (/src/node_modules/passport/lib/authenticator.js:276:7)
    at strategies.ntuvpn.exports.serializeUser (/src/auth.js:54:3)
    at pass (/src/node_modules/passport/lib/authenticator.js:284:9)
    at Authenticator.serializeUser (/src/node_modules/passport/lib/authenticator.js:289:5)
    at IncomingMessage.req.login.req.logIn (/src/node_modules/passport-wsfed-saml2/node_modules/passport/lib/passport/http/request.js:43:29)
...
```

I think this is caused by the conflict between old passport (0.1.x) and the new one (0.3.x).
Can move the passport depenency to the new one? (0.3.x)

**Comment by siacomuzzi** [comment]
Hi @leomao,

How can I reproduce your issue? Are you using the `initialize` middleware?

```
app.configure(function() {
  // ...
  app.use(passport.initialize());
  // ...
});
```

**Comment by leomao** [comment]
Hi @siacomuzzi , thanks for reply!
My configuration is a bit complicated, but I did use `passport.initialize` middleware:

```javascript
app.use(session(sessOptions));

...

app.use(passport.initialize());                                                  
app.use(passport.session());
```

I am not sure how to reproduce this problem. It does not occur every time.
I just googled it and found this jfromaniello/passport.socketio#109.
After changing the passport version from 0.1.x to 0.3.x in passport-wsfed-saml2, the problem disappeared.
So I guess this is the reason.

BTW, I use express 4.0 with passport 0.3.2.

**Comment by siacomuzzi** [comment]
just published `passport-wsfed-saml2@2.4.0` using `passport@0.3.2` as dependency

**Comment by jaredhanson** [comment]
That works, but it'd be preferrable to depend on [`passport-strategy`](https://github.com/jaredhanson/passport-strategy)`@1.0.0`, rather than `passport` as a whole.

**Comment by siacomuzzi** [comment]
agree.

@jaredhanson please review: https://github.com/auth0/passport-wsfed-saml2/pull/21
