### ISSUE TITLE
SLO missing from library

### ISSUE THREAD

**Issue by nzpcmad** [auth0/passport-wsfed-saml2#27]
Is there a reason that the LogoutRequest code was removed?

It's in the original Henri Bergius's passport-saml library.

I see there is a auth0/samlp-logout repository. Is that the way to go?

**Comment by siacomuzzi** [comment]
passport-wsfed-saml2 covers saml and wsfed protocols

If you are working with ADFS (SAML) you can use `https://github.com/auth0/samlp-logout`.

**Comment by nzpcmad** [comment]
OK - thanks - will do.
