### ISSUE TITLE
Minor issue, but realm does not always match audience

### ISSUE THREAD

**Issue by mmayberry** [auth0/passport-wsfed-saml2#28]
In my current usage I was failing on server side validation due to saml.js validateAudience comparing realm not audience to xpath.  
It's a simple fix but I thought I'd bring it to your attention.

**Comment by siacomuzzi** [comment]
Hi,

Could you please show us your SAML assertion? Also, remember that you can disable audience validation using `options.checkAudience` flag.

**Comment by siacomuzzi** [comment]
Please provide me the following:

* From SAML Request, the `Issuer` value
* From SAML Response, the `AudienceRestriction/AudienceRestrictionCondition -> Audience` value

**Comment by mmayberry** [comment]
Issuer: 'http://www.okta.com/**value**

<Audience>  http://localhost:3738/okta/

**Comment by siacomuzzi** [comment]
Looks like a weird scenario where the Audience is different (see http://stackoverflow.com/questions/5194468/saml-2-0-authnrequest-audiencerestriction)

Anyway, if you think your configuration is correct, you can override the `SAML.prototype.validateAudience` method:

```
var VALID_AUDIENCE = '...';

strategy.validateAudience = function (samlAssertion, realm, version) {
  var audience;
  if (version === '2.0') {
    audience = xpath.select("//*[local-name(.)='Conditions']/*[local-name(.)='AudienceRestriction']/*[local-name(.)='Audience']", samlAssertion);
  } else {
    audience = xpath.select("//*[local-name(.)='Conditions']/*[local-name(.)='AudienceRestrictionCondition']/*[local-name(.)='Audience']", samlAssertion);
  }

  if (!audience || audience.length === 0) return false;
  //return cryptiles.fixedTimeComparison(audience[0].textContent, realm);
  return cryptiles.fixedTimeComparison(audience[0].textContent, VALID_AUDIENCE);
};
```

**Comment by mmayberry** [comment]
I'm taking the audience value from the response as a sanity check, but that works thanks.
