### ISSUE TITLE
Request is incomplete with ADFS

### ISSUE THREAD

**Issue by shlatchz** [auth0/passport-wsfed-saml2#5]
When I try to authenticate my application with an ADFS server, the module only sends the whr, wa and wtrealm.
There is no request token that is passed to the ADFS.
There is no username or other identifier passed.
Does it really work with ADFS?
If so, how should I configure it in order for it to work?

Thanks.

**Comment by OwenBrotherwood** [comment]
https://github.com/auth0/passport-wsfed-saml2/issues/14
