### ISSUE TITLE
xmldom dependency issue with Yarn

### ISSUE THREAD

**Issue by MichaelVasseurBE** [auth0/passport-wsfed-saml2#76]
Hi,
We are using passport-wsfed-saml2 in our project and Yarn as the package manager.
We have an error related to the xmldom dependency.
Actually, this dependency is referenced with a path to the project's [master branch](https://github.com/auth0/xmldom/tarball/master).

**As a consequence, we can have errors when the master branch changes while
we did NOT change our packages.json.**

Can you update your dependencies to use a _specific version_ ?

**Comment by MichaelVasseurBE** [comment]
Any update ?

**Comment by mikeops** [comment]
Hi Michael,

Thanks for reporting this issue.

We've switched from using the master branch to using a release tag for the `xmldom` dependency as part of https://github.com/auth0/passport-wsfed-saml2/pull/74

**Comment by MichaelVasseurBE** [comment]
Great news ! I see that this is already delivered in version 3.8 !
